# Generated by Django 2.1.5 on 2019-02-03 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.TextField(blank=True)),
                ('post_creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('poster_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Users')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Threads.Threads')),
            ],
        ),
    ]
